version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realm-export.json:/opt/keycloak/data/import/realm-export.json
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/staff-realm || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s

  backend:
    build:
      context: ./management
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/staff-realm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/staff-realm/protocol/openid-connect/certs
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  frontend:
    build:
      context: ./staff-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: